-- *******************************************************************************************************************;
-- populations_convert_parquet_to_xls.hive;
-- *******************************************************************************************************************;
select '_c0',generation,population,mass10to7th,mass10to8th
from tumorsim.populations 
where tumorid='${env:tumorid}'
;
